name: "[GRAPHDB INT] Sequential update by statuses"

on:
  workflow_dispatch:

jobs:
  update-concepts:
    strategy:
      max-parallel: 1
      matrix:
        statuses:
          - "Qualified,Standard,PreferredStandard,Retired,Candidate,Superseded,Recorded"

    uses: ./.github/workflows/reusable_workflow.yml
    with:
      STATUSES: ${{ matrix.statuses }}
      CLEAR_GRAPH: false
      LINDAS_UPDATE_URL: "https://graphdb.int.cz-aws.net/repositories/lindas"
      LINDAS_QUERY_URL: "https://lindas.int.cz-aws.net/query"
      BASE_API_URL: "https://api.i14y.admin.ch/api/public/v1/concepts/"
    secrets:
      STARDOG_PASSWORD: ${{ secrets.GRAPHDB_PASSWORD_INT }}
      STARDOG_USER: ${{ secrets.GRAPHDB_USER }}
